#:schema node_modules/wrangler/config-schema.json
name = "wedding-cost"
main = "./server.ts"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

kv_namespaces = [{ binding = "cache", id = "507dcff99f374fcbb06e0d7a0ae7fa12" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "npm run build"

[vars]
GITHUB_OWNER = "edmundhung"
GITHUB_REPO = "remix-cloudflare-template"
